### ISSUE TITLE
What does the tech scene look like in Brazil?

### ISSUE THREAD

**Issue by lencioni** [danilovaz/ama#4]
For example, are there lots of job opportunities? Lots of great conferences? Meetups? etc.

**Comment by danilovaz** [comment]
Hey @lencioni I'm glad to reply about it.

Well, Brazil is a huge country. So it is natural that the vast majority of events, meetups and jobs are concentrated in metropolitan areas. But I can say that even in small towns the community is active. The city that concentrates the biggest events is certainly São Paulo. The financial capital of the country.

Our community is huge and united. We have several groups of facebook (back-end, front-end, information security, etc.), community members who create short courses, varied meetups and more. Recently, our community has created [this repository](https://github.com/frontendbr) in order to centralize discussions, events and Front End vacancies. And it's working very well. We have topics about [jobs](https://github.com/frontendbr/vagas/issues), [forum](https://github.com/frontendbr/forum/issues) and [events](https://github.com/frontendbr/eventos/issues)

There are some great companies here in Brazil that hire, even remotely, as you can see [here](https://github.com/lerrua/remote-jobs-brazil). I can say that job openings abound, what is missing are qualified people to fill vacancies.

The salary can vary greatly depending on where the person lives. A senior who works in the city of São Paulo can earn R$ 7,000.00 (about $ 2,000.00), as a senior who works in a small town in the state of São Paulo can earn R$ 3,000.00 (almost $ 900,00).

The world's largest JavaScirpt event happens here in Brazil. It is the [BrazilJS Conf](https://braziljs.org/conf?lang=en) and received many visitors from here and abroad.

What I see interesting here is that the community is concerned to disseminate knowledge and make it reach ever further. Then you will always see initiatives like these: [CerebroBR](https://github.com/cerebrobr) and [Training Center](https://github.com/training-center) and [Frontend-Career](https://github.com/woliveiras/front-end-career) and [Webschool-io](https://github.com/Webschool-io)

Developers here have to be usually multidisciplinary. Even those focuses, for example, only in Ruby is seen at times that have to do with the Front. It is not difficult you find a back-end programmer who understands front, know a thing or two design and UX.

I hope I have answered your question well :smile:

**Comment by lencioni** [comment]
> I hope I have answered your question well :smile:

You have! Thank you. :)

**Comment by danilovaz** [comment]
You're welcome :smiley:
